# JMS properties
guru:
  jms:
    username:  JMS Username from yml file
    password: JMS password
    dburl: JMS dburl
# FIle separator --- Spring profiles overrides file 1 without it
---
spring:
  profiles:  es
guru:
  jms:
    username:  JMS Username in spanish